version: '3'

services:
    mongo_db:
        image: mongo
        restart: unless-stopped
    backend:
        build:
            context: backend
        ports:
            - 5000:5000
        restart: unless-stopped
        environment:
            MONGO_HOST: mongo_db
        depends_on:
            - mongo_db
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/
            ME_CONFIG_BASICAUTH: "false"
        depends_on:
            - mongo_db
        restart: unless-stopped
    gateway:
        image: nginx:latest
        volumes:
            - ./gateway/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8000:80
            - 8001:81
            - 8002:82
        depends_on:
            - mongo_db
        restart: unless-stopped
    grafana:
        image: grafana/grafana-oss
        ports:
        - "80:3000"
        environment:
        - "GF_PATHS_CONFIG=/grafana.ini"
        volumes:
        - ./grafana/conf/grafana.ini:/grafana.ini
        - ./grafana/grafana_db:/var/lib/grafana
    authenticator:
        build:
            context: auth
        ports:
            - 5001:5000
        restart: unless-stopped
        environment:
            MONGO_HOST: mongo_db
            FLASK_APP: auth
            FLASK_ENV: development
        depends_on:
            - mongo_db