version: '3'

services:
    mongo_db:
        image: mongo
        restart: unless-stopped
        networks:
            - db_access
        volumes:
            - db_data:/data/db

    backend:
        build:
            context: backend
        ports:
            - 5000:5000
        restart: unless-stopped
        volumes:
            - ./backend:/worky:ro
        environment:
            MONGO_HOST: mongo_db
        networks:
            - gateway_access
            - db_access
        depends_on:
            - mongo_db
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/
            ME_CONFIG_BASICAUTH: "false"
        depends_on:
            - mongo_db
        networks:
            - gateway_access
            - db_access
        restart: unless-stopped
    gateway:
        image: nginx:latest
        volumes:
            - ./gateway/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8000:80
            - 8001:81
            - 8002:82
        networks:
            - gateway_access
        depends_on:
            - backend
            - authenticator
            - grafana
            - mongo-express
        restart: unless-stopped
    grafana:
        build:
            context: grafana
        ports:
        - "80:3000"
        environment:
        - "GF_PATHS_CONFIG=/grafana.ini"
        networks:
            - gateway_access
            - grafana_access
        volumes:
        # - ./grafana/conf/grafana.ini:/grafana.ini
        # - ./grafana/grafana_db:/var/lib/grafana
            - grafana_data:/var/lib/grafana

    telegraf:
        image: telegraf:latest
        volumes:
            - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
        depends_on:
            - gateway
            - grafana
        restart: unless-stopped
        networks:
            - gateway_access
            - grafana_access

    authenticator:
        build:
            context: auth
        volumes:
            - ./auth:/worky:ro
        ports:
            - 5001:5000
        networks:
            - db_access
            - gateway_access
        restart: unless-stopped
        environment:
            MONGO_HOST: mongo_db
            FLASK_APP: auth
            FLASK_ENV: development
        depends_on:
            - mongo_db

volumes:
    db_data:
    grafana_data:

networks:
    db_access:
    gateway_access:
    grafana_access: