version: '3'

services:
    mongo_db:
        image: mongo
        networks:
            - db_access
        volumes:
            - db_data:/data/db
        
    backend:
        image: ghcr.io/cristisima/idp_backend:master
        environment:
            MONGO_HOST: mongo_db
        networks:
            - gateway_access
            - db_access
        depends_on:
            - mongo_db

    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/
            ME_CONFIG_BASICAUTH: "false"
        networks:
            - gateway_access
            - db_access
        depends_on:
            - mongo_db

    gateway:
        image: ghcr.io/cristisima/idp_gateway:master
        ports:
            - 8000:80
            - 8001:81
            - 8002:82
        networks:
            - gateway_access
        depends_on:
            - backend
            - authenticator
            - grafana
            - mongo-express
    grafana:
        image: ghcr.io/cristisima/idp_grafana:master
        networks:
            - gateway_access
            - grafana_access
        environment:
        - "GF_PATHS_CONFIG=/grafana.ini"
        volumes:
            - grafana_data:/var/lib/grafana

    telegraf:
        image: ghcr.io/cristisima/idp_telegraf:master
        networks:
            - gateway_access
            - grafana_access
        depends_on:
            - gateway
            - grafana

    authenticator:
        image: ghcr.io/cristisima/idp_authenticator:master
        networks:
            - db_access
            - gateway_access
        environment:
            MONGO_HOST: mongo_db
            FLASK_APP: auth
            FLASK_ENV: development
        depends_on:
            - mongo_db

volumes:
    db_data:
    grafana_data:

networks:
    db_access:
    gateway_access:
    grafana_access: